name: (Docker) Build ImmortalWrt

permissions:
  contents: write

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      OpenWrt_Repository:
        description: "ImmortalWrt Repository"
        required: true
        default: "https://github.com/immortalwrt/immortalwrt.git"
        type: string
      OpenWrt_Branch:
        description: "ImmortalWrt Branch"
        required: true
        default: "master"
        type: string
      Target_System:
        description: "Target System"
        required: true
        default: "x86"
        type: choice
        options:
          - "x86"
          - "MediaTek_Ralink_ARM"
          - "MediaTek_Ralink_MIPS"
      Subtarget:
        description: "Subtarget"
        required: true
        default: "x86_64"
        type: choice
        options:
          - "x86_64"
          - "MT798x"
          - "MT7620"
          - "MT7621"
      Target_Profile:
        description: "Target Profile"
        required: false
        default: ""
        type: string
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
        default: ""
      runner_image:
        description: "Runner Image"
        type: string
        required: false
        default: "ubuntu-26.04"
  workflow_call:
    inputs:
      OpenWrt_Repository:
        description: "ImmortalWrt Repository URL"
        required: false
        type: string
        default: "https://github.com/immortalwrt/immortalwrt.git"
      OpenWrt_Branch:
        description: "ImmortalWrt Branch Name"
        required: false
        type: string
        default: "master"
      Target_System:
        description: "Target System"
        required: true
        type: string
      Subtarget:
        description: "Subtarget"
        required: true
        type: string
      Target_Profile:
        description: "Target Profile"
        required: false
        type: string
        default: ""
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
        default: ""
      runner_image:
        description: "Runner Image"
        required: false
        type: string
        default: "ubuntu-26.04"

run-name: ImmortalWrt ${{ inputs.OpenWrt_Branch }} - ${{ inputs.Target_System }} - ${{ inputs.Subtarget }} - ${{ inputs.Target_Profile || inputs.Subtarget }}

jobs:
  build:
    name: ImmortalWrt ${{ inputs.OpenWrt_Branch }} - ${{ inputs.Target_System }} - ${{ inputs.Subtarget }} - ${{ inputs.Target_Profile || inputs.Subtarget }}
    uses: ./.github/workflows/build_openwrt_indocker.yml
    secrets: inherit
    with:
      runner_image: ${{ inputs.runner_image }}
      OpenWrt_Repository: ${{ inputs.OpenWrt_Repository }}
      OpenWrt_Branch: ${{ inputs.OpenWrt_Branch }}
      Target_System: ${{ inputs.Target_System }}
      Subtarget: ${{ inputs.Subtarget }}
      Target_Profile: ${{ inputs.Target_Profile }}
      custom_env: ${{ inputs.custom_env }}
