name: Call Build (Dev)

on:
  schedule:
    # Run every day at 21:00 UTC
    - cron: "0 21 * * *"
  repository_dispatch:
  workflow_dispatch:

run-name: Build Matrix for OpenWrt

jobs:
  openwrt:
    name: ${{ matrix.Branch }}
    uses: ./.github/workflows/build-openwrt_dev.yml
    strategy:
      fail-fast: false
      matrix:
        runner_image: ["ubuntu-24.04"]
        openwrt_branch: ["main", "openwrt-24.10"]
        inputs_params:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: ${{ matrix.openwrt_branch }}
      Target_System: ${{ matrix.inputs_params.Target_System }}
      Subtarget: ${{ matrix.inputs_params.Subtarget }}
      Target_Profile: ${{ matrix.inputs_params.Target_Profile }}
      runner_image: ${{ matrix.runner_image }}
