name: Call Build (Dev)

on:
  workflow_dispatch:

jobs:
  build_x86:
    uses: ./.github/workflows/build-openwrt.yml
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: "main"
      Target_System: "x86"
      Subtarget: "x86_64"
      Target_Profile: ""

  build_mt798x:
    uses: ./.github/workflows/build-openwrt.yml
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: "main"
      Target_System: "MediaTek_Ralink_ARM"
      Subtarget: "MT798x"
      Target_Profile: ""

  build_nokia:
    uses: ./.github/workflows/build-openwrt.yml
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: "main"
      Target_System: "MediaTek_Ralink_ARM"
      Subtarget: "MT798x"
      Target_Profile: "nokia_ea0326gmp"