name: Call Build (Dev)

on:
  workflow_dispatch:

env:
  Branch_Snapshot: "main"
  Branch_Release: "openwrt-24.10"

jobs:
  openwrt:
    name: Snapshot
    uses: ./.github/workflows/build-openwrt_dev.yml
    strategy:
      matrix:
        Branch:
          - ${{ env.Branch_Snapshot }}
          - ${{ env.Branch_Release }}
        build_params:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: ${{ matrix.Branch }}
      Target_System: ${{ matrix.build_params.Target_System }}
      Subtarget: ${{ matrix.build_params.Subtarget }}
      Target_Profile: ${{ matrix.build_params.Target_Profile }}