name: Call Build (Dev)

# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions
run-name: Build Matrix for OpenWrt

on:
  schedule:
    # Run every day at 21:00 UTC
    - cron: "0 21 * * *"
  repository_dispatch:
  workflow_dispatch:

jobs:
  openwrt:
    name: ${{ matrix.openwrt_branch }}
    # continue-on-error: true
    # concurrency:
    #   group: example-group
    #   cancel-in-progress: true
    uses: ./.github/workflows/build-openwrt_dev.yml
    # secrets: inherit
    strategy:
      fail-fast: false
      # max-parallel: 4
      matrix:
        runner_image: ["ubuntu-24.04"]
        openwrt_repo: ["git.openwrt.org/openwrt/openwrt.git"]
        openwrt_branch: ["main", "openwrt-24.10"]
        workflows_inputs:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    with:
      runner_image: ${{ matrix.runner_image }} # || 'ubuntu-24.04'
      OpenWrt_Repository: ${{ matrix.openwrt_repo }}
      OpenWrt_Branch: ${{ matrix.openwrt_branch }}
      Target_System: ${{ matrix.workflows_inputs.Target_System }}
      Subtarget: ${{ matrix.workflows_inputs.Subtarget }}
      Target_Profile: ${{ matrix.workflows_inputs.Target_Profile }}
