name: Call Build (Dev)

on:
  workflow_dispatch:

run-name: Build Matrix for OpenWrt

jobs:
  openwrt:
    name: OpenWrt Branch - ${{ matrix.Branch }}
    uses: ./.github/workflows/build-openwrt_dev.yml
    strategy:
      fail-fast: false
      matrix:
        Branch: ["main", "openwrt-23.05"]
        inputs_params:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    with:
      OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
      OpenWrt_Branch: ${{ matrix.Branch }}
      Target_System: ${{ matrix.inputs_params.Target_System }}
      Subtarget: ${{ matrix.inputs_params.Subtarget }}
      Target_Profile: ${{ matrix.inputs_params.Target_Profile }}