name: Call Build (Docker)

# Github Actions workflow syntax reference:
# https://docs.github.com/zh/actions/reference/workflows-and-actions/workflow-syntax
# https://docs.github.com/zh/actions/reference/workflows-and-actions/metadata-syntax#runs-for-composite-actions
# https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#yaml-anchors-and-aliases

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/call-build_docker.yml"
  schedule:
    # UTC Time
    - cron: "0 22 * * *"
  repository_dispatch:
  workflow_dispatch:

run-name: Build Matrix for OpenWrt (Docker)

jobs:
  runner-image:
    name: ubuntu-latest - runner-image
    runs-on: ubuntu-latest
    outputs:
      RUNNER_IMAGE: ${{ steps.resolve-runner-image.outputs.RUNNER_IMAGE }}
    steps:
      - name: Resolve runner-image
        id: resolve-runner-image
        uses: Grinch27/github-actions/.github/actions/resolve-runner-image@main

  toolchain:
    name: ${{ needs.runner-image.outputs.RUNNER_IMAGE }} - ubuntu:devel - toolchain
    needs: runner-image
    runs-on: ${{ needs.runner-image.outputs.RUNNER_IMAGE }}
    permissions: write-all
    defaults:
      run:
        shell: bash
    container:
      image: &container_image ubuntu:devel
      options: &container_options >-
        --privileged
        --user=0:0
        --pid=host
        --ipc=host
        --uts=host
        --cgroupns=host
        --cap-add=ALL
        --security-opt apparmor=unconfined
        --security-opt seccomp=unconfined
        --init
        --pids-limit=-1
        --shm-size=12g
        --ulimit nofile=1048576:1048576
      volumes: &container_volumes
        - /dev:/dev
        - /sys:/sys:rw
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
        - /run/udev:/run/udev:ro
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock
    env:
      DEBIAN_FRONTEND: noninteractive
      FORCE_UNSAFE_CONFIGURE: "1"
    outputs:
      gcc_version: ${{ steps.resolve-toolchain.outputs.gcc_version }}
      clang_version: ${{ steps.resolve-toolchain.outputs.clang_version }}
      jdk_version: ${{ steps.resolve-toolchain.outputs.jdk_version }}
      custom_env: ${{ steps.resolve-toolchain.outputs.custom_env }}
    steps:
      - name: Resolve toolchain versions
        id: resolve-toolchain
        uses: Grinch27/github-actions/.github/actions/resolve-toolchain-version@main

  heads:
    name: Heads of ${{ matrix.repo_target }}
    needs: runner-image
    runs-on: ${{ needs.runner-image.outputs.RUNNER_IMAGE }}
    permissions: write-all
    defaults:
      run:
        shell: bash
    container:
      image: *container_image
      options: *container_options
      volumes: *container_volumes
    env:
      DEBIAN_FRONTEND: noninteractive
      FORCE_UNSAFE_CONFIGURE: "1"
    outputs:
      repo_branch: ${{ steps.git-heads.outputs.repo_branch }}
    strategy:
      fail-fast: false
      matrix:
        repo_target: ["https://github.com/openwrt/openwrt.git"]
    steps:
      - name: git Ensure
        id: git-install
        run: |
          set -euo pipefail
          command -v git >/dev/null 2>&1 && git --version && exit 0
          if [[ "$(id -u)" -eq 0 ]]; then
            apt-get update
            env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git ca-certificates
          else
            sudo apt-get update
            sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git ca-certificates
          fi
          git --version

      - name: Get the latest openwrt version branch
        id: git-heads
        run: |
          repo_head=$(git ls-remote --heads ${{ matrix.repo_target }} \
            | grep 'refs/heads/openwrt-[0-9]\+\.[0-9]\+$' \
            | sed 's/.*refs\/heads\/openwrt-//' \
            | sort -V \
            | tail -n1)
          echo "repo_branch=openwrt-$repo_head" | tee -a $GITHUB_OUTPUT

  action:
    name: ${{ matrix.openwrt_branch }}
    needs:
      - runner-image
      - toolchain
      - heads
    permissions: write-all
    uses: ./.github/workflows/build_openwrt_indocker.yml
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        openwrt_repo: ["https://github.com/openwrt/openwrt.git"]
        openwrt_branch:
          - "main"
          - "${{ needs.heads.outputs.repo_branch }}"
        workflows_inputs:
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "MT798x_docker"
          - Target_System: "MediaTek_Ralink_MIPS"
            Subtarget: "MT7621"
            Target_Profile: ""
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
        # exclude:
        #   - openwrt_branch: "${{ needs.heads.outputs.repo_branch }}"
        #     workflows_inputs:
        #       Target_System: "x86"
        #       Subtarget: "x86_64"
        #       Target_Profile: ""
    with:
      # ========== Base ==========
      RUNNER_IMAGE: ${{ needs.runner-image.outputs.RUNNER_IMAGE }}
      # ========== OpenWrt ==========
      OpenWrt_Repository: ${{ matrix.openwrt_repo }}
      OpenWrt_Branch: ${{ matrix.openwrt_branch }}
      Target_System: ${{ matrix.workflows_inputs.Target_System }}
      Subtarget: ${{ matrix.workflows_inputs.Subtarget }}
      Target_Profile: ${{ matrix.workflows_inputs.Target_Profile }}
