name: Call Build (Dev)

on:
  workflow_dispatch:

env:
  OpenWrt_Repository: "git.openwrt.org/openwrt/openwrt.git"
  Workflow_Path: ".github/workflows/build-openwrt_dev.yml"

jobs:
  snapshot:
    name: Snapshot
    strategy:
      matrix:
        build_params:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    uses: ${{ env.Workflow_Path }}
    with:
      OpenWrt_Repository: ${{ env.OpenWrt_Repository }}
      OpenWrt_Branch: "main"
      Target_System: ${{ matrix.build_params.Target_System }}
      Subtarget: ${{ matrix.build_params.Subtarget }}
      Target_Profile: ${{ matrix.build_params.Target_Profile }}

  stable:
    name: Stable
    strategy:
      matrix:
        build_params:
          - Target_System: "x86"
            Subtarget: "x86_64"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: ""
          - Target_System: "MediaTek_Ralink_ARM"
            Subtarget: "MT798x"
            Target_Profile: "nokia_ea0326gmp"
    uses: ${{ env.Workflow_Path }}
    with:
      OpenWrt_Repository: ${{ env.OpenWrt_Repository }}
      OpenWrt_Branch: "openwrt-23.05"
      Target_System: ${{ matrix.build_params.Target_System }}
      Subtarget: ${{ matrix.build_params.Subtarget }}
      Target_Profile: ${{ matrix.build_params.Target_Profile }}