name: Cleanup Release and Tag (Dev)

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: "关键字，用于匹配需要删除的 release 和 tag"
        required: true
        default: "6.6.60"

run-name: Release and Tag - ${{ inputs.keyword }}

jobs:
  delete:
    name: ${{ inputs.keyword }}
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get -y update && sudo apt-get -y install gh

      - name: Auth with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete releases and tags with keyword
        run: |
          KEYWORD="${{ inputs.keyword }}"
          REPO="${GITHUB_REPOSITORY}"
      
          # 通过 API 获取所有 releases 再过滤，避免命令行解析错误
          echo "Processing releases..."
          gh api repos/$REPO/releases --paginate | jq -r --arg kw "$KEYWORD" '.[] | select(.tag_name | contains($kw)) | .id' | while read -r id; do
            if [ -n "$id" ]; then
              echo "Deleting release ID: $id"
              gh api --method DELETE "repos/$REPO/releases/$id" || true
            fi
          done
      
          # 删除匹配的 tags
          echo "Processing tags..."
          gh api repos/$REPO/git/refs/tags | jq -r --arg kw "$KEYWORD" '.[] | select(.ref | contains($kw)) | .ref' | while read -r ref; do
            if [ -n "$ref" ]; then
              echo "Deleting tag: $ref"
              gh api --method DELETE "repos/$REPO/git/$ref" || true
            fi
          done