name: Cleanup Release and Tag (Dev)

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: "关键字，用于匹配需要删除的 release 和 tag"
        required: true
        default: "6.6.60"

run-name: Release and Tag - ${{ inputs.keyword }}

jobs:
  delete:
    name: ${{ inputs.keyword }}
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get -y update && sudo apt-get -y install gh

      - name: Auth with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete releases and tags with keyword
        run: |
          # 删除匹配的 Releases
          for tag in $(gh release list --repo "$GITHUB_REPOSITORY" --limit 100 | grep "${{ inputs.keyword }}" | awk '{print $1}'); do
            echo "Deleting release: $tag"
            gh release delete "$tag" --repo "$GITHUB_REPOSITORY" -y || true
          done
      
          # 删除匹配的 Tags
          for ref in $(gh api repos/$GITHUB_REPOSITORY/git/refs/tags | jq -r '.[] | select(.ref | contains("'"${{ inputs.keyword }}"'")) | .ref'); do
            echo "Deleting tag: $ref"
            gh api --method DELETE repos/$GITHUB_REPOSITORY/git/$ref || true
          done