name: Heads (Dev)

# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
run-name: Heads of Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  heads:
    runs-on: ubuntu-latest
    env:
      REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
    outputs:
      latest_branch: ${{ steps.find_latest.outputs.latest_branch }}
    steps:
      - name: Get the latest openwrt version branch
        id: find_latest
        run: |
          latest_version=$(git ls-remote --heads ${{ env.REPO_URL }} \
            | grep 'refs/heads/openwrt-[0-9]\+\.[0-9]\+$' \
            | sed 's/.*refs\/heads\/openwrt-//' \
            | sort -V \
            | tail -n1)
          echo "latest_branch=openwrt-$latest_version" >> $GITHUB_OUTPUT

      - name: Check the latest branch
        id: check
        run: |
          echo "The latest branch is: ${{ steps.find_latest.outputs.latest_branch }}"
