name: Heads (Dev)

# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions
run-name: Heads of Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  heads:
    runs-on: ubuntu-latest
    env:
      REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
    steps:
      - name: 获取最新的 openwrt 版本分支
        id: find_latest
        run: |
          latest_version=$(git ls-remote --heads ${{ env.REPO_URL }} \
            | grep 'refs/heads/openwrt-[0-9]\+\.[0-9]\+$' \
            | sed 's/.*refs\/heads\/openwrt-//' \
            | sort -V \
            | tail -n1)
          echo "latest_branch=openwrt-$latest_version" >> $GITHUB_OUTPUT

      - name: 输出最新分支
        run: echo "最新的分支是 ${{ steps.find_latest.outputs.latest_branch }}"
