name: Heads (Dev)

# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
run-name: Heads of Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  heads:
    name: ${{ matrix.repo_target }}
    runs-on: ${{ matrix.runner_image || 'ubuntu-latest' }}
    outputs:
      latest_branch: ${{ steps.find_latest.outputs.latest_branch }}
    strategy:
      fail-fast: false
      matrix:
        runner_image: ["ubuntu-latest"]
        repo_target: ["https://git.openwrt.org/openwrt/openwrt.git"]
    steps:
      - name: Get the latest openwrt version branch
        id: find_latest
        run: |
          latest_version=$(git ls-remote --heads ${{ matrix.repo_target }} \
            | grep 'refs/heads/openwrt-[0-9]\+\.[0-9]\+$' \
            | sed 's/.*refs\/heads\/openwrt-//' \
            | sort -V \
            | tail -n1)
          echo "latest_branch=openwrt-$latest_version" >> $GITHUB_OUTPUT

      - name: Check the latest branch
        id: check
        run: |
          echo "The latest branch is: ${{ steps.find_latest.outputs.latest_branch }}"
